In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset=pd.read_csv(r'D:\Data centr\Exel_data\own data\salary.csv')

In [3]:
dataset


Unnamed: 0  country   age   salary purched
0           0   france  44.0  72000.0      no
1           1    spain  27.0  48000.0     yes
2           2  germany  30.0  54000.0      no
3           3    spain  38.0  61000.0      no
4           4  germany  40.0      NaN     yes
5           5   france  35.0  58000.0     yes
6           6    spain   NaN  52000.0      no
7           7   france  48.0  79000.0     yes
8           8  germany  50.0  83000.0      no

In [4]:
x=dataset[['country','age','salary']]

In [5]:
x

country   age   salary
0   france  44.0  72000.0
1    spain  27.0  48000.0
2  germany  30.0  54000.0
3    spain  38.0  61000.0
4  germany  40.0      NaN
5   france  35.0  58000.0
6    spain   NaN  52000.0
7   france  48.0  79000.0
8  germany  50.0  83000.0

In [6]:
y=dataset[['purched']]

In [7]:
y

purched
0      no
1     yes
2      no
3      no
4     yes
5     yes
6      no
7     yes
8      no

In [8]:
from sklearn.impute import SimpleImputer

In [9]:
imputer=SimpleImputer(missing_values=np.nan,strategy='mean')

In [10]:
imputer

SimpleImputer()

In [11]:

imputer = imputer.fit(x.iloc[:, 1:3])


In [12]:
x.iloc[:, 1:3] = imputer.transform(x.iloc[:, 1:3])



C:\Users\himan\AppData\Local\Temp\ipykernel_12244\4041662233.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x.iloc[:, 1:3] = imputer.transform(x.iloc[:, 1:3])


In [13]:
x

country   age   salary
0   france  44.0  72000.0
1    spain  27.0  48000.0
2  germany  30.0  54000.0
3    spain  38.0  61000.0
4  germany  40.0  63375.0
5   france  35.0  58000.0
6    spain  39.0  52000.0
7   france  48.0  79000.0
8  germany  50.0  83000.0

In [14]:
from sklearn.preprocessing import LabelEncoder

In [15]:
label_encoder_x=LabelEncoder()

In [16]:
x.iloc[:, 0] = label_encoder_x.fit_transform(x.iloc[:, 0])


C:\Users\himan\AppData\Local\Temp\ipykernel_12244\3564148587.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x.iloc[:, 0] = label_encoder_x.fit_transform(x.iloc[:, 0])
C:\Users\himan\AppData\Local\Temp\ipykernel_12244\3564148587.py:1: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  x.iloc[:, 0] = label_encoder_x.fit_transform(x.iloc[:, 0])


In [17]:
x

country   age   salary
0        0  44.0  72000.0
1        2  27.0  48000.0
2        1  30.0  54000.0
3        2  38.0  61000.0
4        1  40.0  63375.0
5        0  35.0  58000.0
6        2  39.0  52000.0
7        0  48.0  79000.0
8        1  50.0  83000.0

In [18]:
from sklearn.preprocessing import OneHotEncoder

In [19]:
onehotencoder=OneHotEncoder()

In [20]:
x=onehotencoder.fit_transform(dataset.country.values.reshape(-1,1)).toarray()

In [21]:
x

array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [22]:
labelencoder_y=LabelEncoder()

In [23]:
y=labelencoder_y.fit_transform(y)

d:\program\conda\lib\site-packages\sklearn\preprocessing\_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [24]:
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0])

In [25]:
from sklearn.model_selection import train_test_split

In [26]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [27]:
x_train

array([[0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.]])

In [28]:
x_test

array([[1., 0., 0.],
       [0., 1., 0.]])

In [29]:
y_train

array([1, 1, 0, 0, 0, 0, 1])

In [30]:
y_test

array([1, 0])

In [31]:
from sklearn.preprocessing import StandardScaler

In [32]:
Sc_x=StandardScaler()

In [33]:
x_train=Sc_x.fit_transform(x_train)

In [34]:
x_test=Sc_x.transform(x_test)

In [35]:
x_train

array([[-0.63245553, -0.63245553,  1.15470054],
       [-0.63245553,  1.58113883, -0.8660254 ],
       [-0.63245553,  1.58113883, -0.8660254 ],
       [-0.63245553, -0.63245553,  1.15470054],
       [-0.63245553, -0.63245553,  1.15470054],
       [ 1.58113883, -0.63245553, -0.8660254 ],
       [ 1.58113883, -0.63245553, -0.8660254 ]])

In [36]:
x_test

array([[ 1.58113883, -0.63245553, -0.8660254 ],
       [-0.63245553,  1.58113883, -0.8660254 ]])